### ISSUE TITLE
Choose a database for long-term storage

### ISSUE THREAD

**Issue by ChronosX88** [signaller-matrix/signaller#6]
I suggest using MongoDB, because it is very suitable for storing events.

**Comment by nxshock** [comment]
I prefer pure Go key/value stores like:
- [slowpoke](https://github.com/recoilme/slowpoke)
- [pudge](https://github.com/recoilme/pudge)

**Comment by ChronosX88** [comment]
I'd suggest [Cayley](https://github.com/cayleygraph/cayley)

**Comment by ChronosX88** [comment]
We may use Cayley later, and now we can use [tiedot](https://github.com/HouzuoGuo/tiedot) as temporary solution.

**Comment by ChronosX88** [comment]
Finally, we will use [BuntDB](https://github.com/tidwall/buntdb).
